variables:
  # GITLAB_PERSO_ACCESS_TOKEN_NAME: "VM-UI-TokenTil2020"
  # GITLAB_PERSO_ACCESS_TOKEN_PATH: "/home/gitlab-runner/.gitlabcredentials/PERSO_ACCESS_TOKEN.txt"

before_script:
  - docker info

pull_server_image:
  script:
    - echo "$BESSPIN_GALOIS_ARTIFACTORY" | docker login --username besspin_galois --password-stdin artifactory.galois.com:5001 $BESSPIN_GALOIS_ARTIFACTORY || true
    - docker pull artifactory.galois.com:5008/besspin-ui:latest
  tags:
    - "besspin-ui-tag"

test_server:
  script:
    - docker run besspin-ui:latest sh -c 'cd server && flask test unit'
  tags:
    - "besspin-ui-tag"

build_ui_image:
  script:
    - docker build -f client/Dockerfile -t besspin-ui-client .
  tags:
    - "besspin-ui-tag"

test_ui:
  script:
    - docker run --env CI=true besspin-ui-client:latest npm test
  tags:
    - "besspin-ui-tag"
