before_script:
  - docker info

pull_server_image:
  script:
    - docker pull artifactory.galois.com:5008/besspin-ui:latest
  tags:
    - "besspin-ui-tag"

test_server:
  script:
    - docker run besspin-ui:latest sh -c 'cd server && flask test unit'
  tags:
    - "besspin-ui-tag"

build_ui_image:
  script:
    - docker build -f client/Dockerfile -t besspin-ui-client .
  tags:
    - "besspin-ui-tag"

test_ui:
  script:
    - docker run --env CI=true besspin-ui-client:latest npm test
  tags:
    - "besspin-ui-tag"
