variables:
  GITLAB_PERSO_ACCESS_TOKEN_NAME: "VM-UI-TokenTil2020"
  GITLAB_PERSO_ACCESS_TOKEN_PATH: "/home/gitlab-runner/.gitlabcredentials/PERSO_ACCESS_TOKEN.txt"

before_script:
  - docker info

build_image:
  script:
    - docker build -f Dockerfile --build-arg TOKEN_NAME=$GITLAB_PERSO_ACCESS_TOKEN_NAME --build-arg PRIVATE_TOKEN="$(cat $GITLAB_PERSO_ACCESS_TOKEN_PATH)" -t besspin-ui .
  tags:
    - "besspin-ui-tag"

test_server:
  script:
    - docker run besspin-ui:latest sh -c 'cd server && flask test unit'
  tags:
    - "besspin-ui-tag"
