# Dockerfile-besspin-base
#
# Purpose: This is a base image that installs basic tools needed for all
#          besspin toolsuite/ui related images as well as setting up the
#          "besspinuser"
FROM debian:10

# Adapted from https://github.com/holochain/holonix/pull/63/files
WORKDIR /

RUN apt-get update && \
    apt-get install -y software-properties-common && \
    apt-get install -y sudo xz-utils curl ssh git tar && \
    adduser --disabled-password --gecos '' besspinuser && \
    adduser besspinuser sudo && \
    echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers && \
    addgroup --system nixbld && \
    adduser besspinuser nixbld

# use the besspinuser user
USER besspinuser
ENV USER besspinuser

WORKDIR /home/besspinuser

RUN mkdir /home/besspinuser/.ssh/ && \
    touch /home/besspinuser/.ssh/known_hosts && \
    ssh-keyscan gitlab-ext.galois.com >> /home/besspinuser/.ssh/known_hosts
