# To build this Dockerfile do the build with the environment variables
# BINCACHE_LOGIN, BINCACHE_APIKEY, TOKEN_NAME, PRIVATE_TOKEN

# docker build -f Dockerfile-toolsuite --build-arg BINCACHE_LOGIN=$ARTIFACTORY_LOGIN --build-arg BINCACHE_APIKEY="$(cat ~/.ssh/artifactory_api_key)" --build-arg TOKEN_NAME=$GITLAB_PERSO_ACCESS_TOKEN --build-arg PRIVATE_TOKEN="$(cat ~/.ssh/PERSO_ACCESS_TOKEN.txt)" -t besspin-toolsuite-image .

FROM ubuntu:bionic

RUN apt-get update && \
    apt-get install -y software-properties-common && \
    add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu/ bionic universe multiverse"

RUN apt-get install -y python3-pip sqlite3
RUN pip3 install flask nose

# Adapted from https://github.com/holochain/holonix/pull/63/files
WORKDIR /

RUN apt-get install -y sudo xz-utils curl ssh
RUN adduser --disabled-password --gecos '' besspinuser
RUN adduser besspinuser sudo
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

# nix expects the nixbld group
RUN addgroup --system nixbld
RUN adduser besspinuser nixbld

# use the besspinuser user
USER besspinuser
ENV USER besspinuser
WORKDIR /home/besspinuser

# disable nix sandboxing in docker
RUN mkdir -p /home/besspinuser/.config/nix && echo 'sandbox = false' > /home/besspinuser/.config/nix/nix.conf

# Add some configuration settings to nix.conf
RUN echo 'trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= besspin.galois.com-1:8IqXQ2FM1J5CuPD+KN9KK4z6WHve4KF3d9zGRK+zsBw=' >> /home/besspinuser/.config/nix/nix.conf && \
    echo 'substituters = https://artifactory.galois.com/besspin_generic-nix/ https://cache.nixos.org/' >> /home/besspinuser/.config/nix/nix.conf && \
    echo 'netrc-file = /home/besspinuser/.config/nix/netrc' >> /home/besspinuser/.config/nix/nix.conf


# Set the login and APIKET for artifactory
ARG BINCACHE_LOGIN
ARG BINCACHE_APIKEY
RUN echo 'machine artifactory.galois.com' > /home/besspinuser/.config/nix/netrc && \
    echo "login ${BINCACHE_LOGIN}" >> /home/besspinuser/.config/nix/netrc && \
    echo "password ${BINCACHE_APIKEY}" >> /home/besspinuser/.config/nix/netrc

#RUN cat /home/besspinuser/.config/nix/netrc
#RUN cat /home/besspinuser/.config/nix/nix.conf

WORKDIR /home/besspinuser/

# https://nixos.wiki/wiki/Nix_Installation_Guide#Single-user_install
RUN sudo install -d -m755 -o $(id -u) -g $(id -g) /nix
RUN curl https://nixos.org/nix/install | sh

ARG TOKEN_NAME
ARG PRIVATE_TOKEN
RUN mkdir /home/besspinuser/.ssh/
RUN touch /home/besspinuser/.ssh/known_hosts
RUN ssh-keyscan gitlab-ext.galois.com >> /home/besspinuser/.ssh/known_hosts

RUN sudo apt-get install -y git
RUN touch /home/besspinuser/.gitconfig && \
    echo "[url \"https://${TOKEN_NAME}:${PRIVATE_TOKEN}@gitlab-ext.galois.com/\"]\n\
    insteadOf = \"git@gitlab-ext.galois.com:\"\n\
[url \"git@gitlab-ext.galois.com:\"]\n\
    pushInsteadOf = \"git@gitlab-ext.galois.com:\"" >> /home/besspinuser/.gitconfig


#RUN cat /home/besspinuser/.gitconfig
RUN git clone "https://${TOKEN_NAME}:${PRIVATE_TOKEN}@gitlab-ext.galois.com/ssith/tool-suite.git"
WORKDIR /home/besspinuser/tool-suite
RUN git checkout develop

RUN sudo curl --netrc-file /home/besspinuser/.config/nix/netrc https://artifactory.galois.com/besspin_generic-nix/nix-cache-info
RUN . $HOME/.nix-profile/etc/profile.d/nix.sh && nix-shell
