# Dockerfile-toolsuite
#
# Purpose: overlays necessary Nix and toolsuite-related libraries on top of the
#          besspin-user-image

ARG BESSPIN_BASE_VERSION=latest
FROM artifactory.galois.com:5008/besspin-base-user:${BESSPIN_BASE_VERSION}

USER besspinuser
ENV USER besspinuser

WORKDIR /home/besspinuser

# disable nix sandboxing in docker
RUN mkdir -p /home/besspinuser/.config/nix && \
    echo 'sandbox = false' > /home/besspinuser/.config/nix/nix.conf

# Add some configuration settings to nix.conf
RUN echo 'trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= besspin.galois.com-1:8IqXQ2FM1J5CuPD+KN9KK4z6WHve4KF3d9zGRK+zsBw=' >> /home/besspinuser/.config/nix/nix.conf && \
    echo 'substituters = https://artifactory.galois.com/artifactory/besspin_generic-nix/ https://cache.nixos.org/' >> /home/besspinuser/.config/nix/nix.conf && \
    echo 'netrc-file = /home/besspinuser/.config/nix/netrc' >> /home/besspinuser/.config/nix/nix.conf

# Set the login and APIKEY for artifactory
ARG BINCACHE_LOGIN
ARG BINCACHE_APIKEY
RUN echo 'machine artifactory.galois.com' > /home/besspinuser/.config/nix/netrc && \
    echo "login ${BINCACHE_LOGIN}" >> /home/besspinuser/.config/nix/netrc && \
    echo "password ${BINCACHE_APIKEY}" >> /home/besspinuser/.config/nix/netrc

# TODO: switching to tar file would reduce the image size (by a smidgen)
RUN git clone --depth=1 --single-branch --branch=master https://github.com/bluespec/Piccolo.git

# https://nixos.wiki/wiki/Nix_Installation_Guide#Single-user_install
RUN sudo install -d -m755 -o $(id -u) -g $(id -g) /nix
RUN curl --silent https://nixos.org/nix/install | sh

ARG TOKEN_NAME
ARG PRIVATE_TOKEN

RUN touch /home/besspinuser/.gitconfig && \
    echo "[url \"https://${TOKEN_NAME}:${PRIVATE_TOKEN}@gitlab-ext.galois.com/\"]\n\
    insteadOf = \"git@gitlab-ext.galois.com:\"\n\
[url \"git@gitlab-ext.galois.com:\"]\n\
    pushInsteadOf = \"git@gitlab-ext.galois.com:\"" >> /home/besspinuser/.gitconfig

ARG TOOLSUITE_BRANCH=master
ARG TESTGEN_BRANCH=master

WORKDIR /home/besspinuser
RUN git clone --depth 1 --single-branch --branch ${TOOLSUITE_BRANCH} "https://${TOKEN_NAME}:${PRIVATE_TOKEN}@gitlab-ext.galois.com/ssith/tool-suite.git"

WORKDIR /home/besspinuser/tool-suite

RUN sudo curl --silent https://$BINCACHE_LOGIN:$BINCACHE_APIKEY@artifactory.galois.com/artifactory/besspin_generic-nix/nix-cache-info
RUN . $HOME/.nix-profile/etc/profile.d/nix.sh && nix-shell

WORKDIR /home/besspinuser

# NOTE: because testgen has submodules, we cannot fetch a tar file
RUN git clone --depth 1 --single-branch --branch $TESTGEN_BRANCH "https://${TOKEN_NAME}:${PRIVATE_TOKEN}@gitlab-ext.galois.com/ssith/testgen.git"

WORKDIR /home/besspinuser/testgen

RUN git submodule update --init --recursive
RUN . $HOME/.nix-profile/etc/profile.d/nix.sh && nix-shell

WORKDIR /home/besspinuser

RUN rm /home/besspinuser/.gitconfig
