"""workflow and report

Revision ID: 550bf0061d43
Revises: 12b5476aac79
Create Date: 2020-01-14 11:40:56.619851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '550bf0061d43'
down_revision = '12b5476aac79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'reportJobs',
        sa.Column('jobId', sa.Integer(), nullable=False),
        sa.Column('sysConfigId', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['jobId'], ['jobs.jobId'], ),
        sa.ForeignKeyConstraint(['sysConfigId'], ['systemConfigurationInputs.sysConfigId'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('jobId')
    )
    op.create_table(
        'workflows',
        sa.Column('label', sa.String(length=128), nullable=True, comment='user-defined label for usability'),
        sa.Column('createdAt', sa.DateTime(), nullable=False),
        sa.Column('updatedAt', sa.DateTime(), nullable=True),
        sa.Column('workflowId', sa.Integer(), nullable=False),
        sa.Column('sysConfigId', sa.Integer(), nullable=True),
        sa.Column('testRunId', sa.Integer(), nullable=True),
        sa.Column('reportJobId', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['reportJobId'], ['reportJobs.jobId'], ),
        sa.ForeignKeyConstraint(['sysConfigId'], ['systemConfigurationInputs.sysConfigId'], ),
        sa.ForeignKeyConstraint(['testRunId'], ['testRunInputs.testRunId'], ),
        sa.PrimaryKeyConstraint('workflowId'),
        sa.UniqueConstraint('sysConfigId', 'testRunId', 'reportJobId', name='workflow_uc')
    )
    op.create_unique_constraint('system_config_inputs_uc', 'systemConfigurationInputs', ['nixConfig'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workflows')
    op.drop_table('reportJobs')
    # ### end Alembic commands ###
